### ISSUE TITLE
Can the edgeEngine Runtime be installed on a microcontroller ?

### ISSUE THREAD

**Issue by theagilecoder** [mimikgit/cocoapod-EdgeEngine#1]
The documentation states:

The edgeEngine Runtime will run on any device that has an operating system that the runtime supports. The following list describes the operating systems supported by the edgeEngine Runtime

Android
iOS
Windows
macOS
Raspian
Linux Ubuntu
Beaglebone
QNX

Source: https://devdocs.mimik.com/key-concepts/01-index

All the above options are microprocessors. Wanted to confirm any microcontroller support for  edgeEngine Runtime....

**Comment by mimikrb** [comment]
Thank you for your interest in edgeEngine.
Since this is a cocoapod github page, I'd suggest to reach out to mimik support at: https://developer.mimik.com/support/
Or join the community discussion at: https://github.com/orgs/edgeEngine/discussions and ask the question there.
